# Docker image for Aconf WH Receiver

FROM python:3.8.10

RUN export DEBIAN_FRONTEND=noninteractive && apt-get update \
&& apt-get install -y --no-install-recommends
RUN mkdir /usr/src/app
WORKDIR /usr/src/app
COPY ./requirements-acwr.txt .
RUN pip3 install -r requirements-acwr.txt
ENV PYTHONUNBUFFERED 1
COPY ./acwreceiver/start_whreceiver.py /usr/src/app/start_whreceiver.py

CMD ["python3", "start_whreceiver.py"]
