version: '3.5'
services:
  grafana:
  container_name: grafana
  restart: always
    build:
      context: ./PogoStats
      dockerfile: Dockerfile.grafana
      args:
        - GF_INSTALL_IMAGE_RENDERER_PLUGIN=true
        - GRAFANA_VERSION=latest
    environment: 
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      GF_SERVER_DOMAIN: ${GF_SERVER_DOMAIN}
      GF_SERVER_ROOT_URL: ${GF_SERVER_ROOT_URL}
    volumes:
      - ./PogoStats/grafana_data:/var/lib/grafana
      - ./PogoStats/grafana/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
      - ./PogoStats/grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
      - ./PogoStats/grafana/dashboards/:/etc/grafana/provisioning/dashboards/
    depends_on:
      - pgsdb
    networks:
      - default
    ports:
      - "${GRAFANA_PORT}:3000"

  pgsdb:
    container_name: pgsdb
    restart: always
    image: mariadb:10.3
    volumes:
      - ./PogoStats/db:/var/lib/mysql
      - ./PogoStats/sql:/docker-entrypoint-initdb.d
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--innodb-flush-method=littlesync', '--innodb-use-native-aio=OFF']
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - default
    ports:
      - "3308:3306"

  pgsapp:
    container_name: pgsapp
    restart: always
    build:
      context: ./PogoStats
    volumes:
      - ${MYSQL_SOCK}:/run/mysqld/mysqld.sock
    environment: 
      GRAFANA_DATABASE: ${MYSQL_DATABASE}
      GRAFANA_USER: ${MYSQL_USER}
      MYSQL_PWD: ${MYSQL_PASSWORD}
      MYSQL_CONNECTION_TYPE: ${MYSQL_CONNECTION_TYPE}
      SCANNER_TYPE: ${SCANNER_TYPE}
      SCANNER_HOST: ${SCANNER_HOST}
      SCANNER_PORT: ${SCANNER_PORT}
      SCANNER_USER: ${SCANNER_USER}
      SCANNER_PASSWORD: ${SCANNER_PASSWORD}
      SCANNER_DATABASE: ${SCANNER_DATABASE}
      STATUS_DOWN: ${STATUS_DOWN}
      CLEANUP_DAYS: ${CLEANUP_DAYS}
    depends_on:
      - pgsdb
    networks:
      - default

  acwr:
    container_name: acwr
    build:
      context: ./PogoStats
      dockerfile: Dockerfile.acwr
    restart: always
    tty: true
    environment: 
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./PogoStats/acwreceiver/config.ini:/usr/src/app/config.ini
    depends_on:
      - pgsdb
    networks:
      - default
    ports:
      - "3050:3050"
