{
 "title": "Poké Metrics",
 "description": "Dashboard to show all graphs of the collected data",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Current Pokémon",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  value AS \"Pokémon\"\nFROM pokemon_data\nWHERE\n  $__timeFilter(timestamp)\nORDER BY timestamp"
    },
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  value AS \"IV\"\nFROM iv_data\nWHERE\n  $__timeFilter(timestamp)\nORDER BY timestamp"
    },
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  value AS \"Nearby\"\nFROM nearby_data\nWHERE\n  $__timeFilter(timestamp)\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Current Raids",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  raids_total AS \"Total Raids\"\nFROM raid_data\nWHERE\n  $__timeFilter(timestamp)\nORDER BY timestamp"
    },
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  raids_1 AS \"Level 1\"\nFROM raid_data\nWHERE\n  $__timeFilter(timestamp)\nORDER BY timestamp"
    },
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  raids_3 AS \"Level 3\"\nFROM raid_data\nWHERE\n  $__timeFilter(timestamp)\nORDER BY timestamp"
    },
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  raids_5 AS \"Level 5\"\nFROM raid_data\nWHERE\n  $__timeFilter(timestamp)\nORDER BY timestamp"
    },
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  raids_6 AS \"Level 6\"\nFROM raid_data\nWHERE\n  $__timeFilter(timestamp)\nORDER BY timestamp"
    },
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  raids_7 AS \"Level 7\"\nFROM raid_data\nWHERE\n  $__timeFilter(timestamp)\nORDER BY timestamp"
    },
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  raids_8 AS \"Level 8\"\nFROM raid_data\nWHERE\n  $__timeFilter(timestamp)\nORDER BY timestamp"
    },
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  raids_9 AS \"Level 9\"\nFROM raid_data\nWHERE\n  $__timeFilter(timestamp)\nORDER BY timestamp"
    },
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  raids_10 AS \"Level 10\"\nFROM raid_data\nWHERE\n  $__timeFilter(timestamp)\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Team GO Rocket Stops",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  value_total AS \"Rocket Stops\"\nFROM tr_data\nWHERE\n  $__timeFilter(timestamp)\nORDER BY timestamp"
    },
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  grunt AS \"Grunt Rocket Stops\"\nFROM tr_data\nWHERE\n  $__timeFilter(timestamp)\nORDER BY timestamp"
    },
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  boss AS \"Boss Rocket Stops\"\nFROM tr_data\nWHERE\n  $__timeFilter(timestamp)\nORDER BY timestamp"
    },
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  npc AS \"NPC Stops\"\nFROM tr_data\nWHERE\n  $__timeFilter(timestamp)\nORDER BY timestamp"
    },
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  kecleon AS \"Kecleon Eventstops\"\nFROM tr_data\nWHERE\n  $__timeFilter(timestamp)\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Quests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  value_total AS \"Total Quests\"\nFROM quest_data\nWHERE\n  $__timeFilter(timestamp)\nORDER BY timestamp"
    },
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  value AS \"Quests mit AR\"\nFROM quest_data\nWHERE\n  $__timeFilter(timestamp)\nORDER BY timestamp"
    },
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  value_alt AS \"Quests ohne AR\"\nFROM quest_data\nWHERE\n  $__timeFilter(timestamp)\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Unknown Spawnpoints in the last 24h",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  value AS \"Unkown Spawnpoints\"\nFROM spawnpoint_data\nWHERE\n  $__timeFilter(timestamp)\nORDER BY timestamp"
    }
   ]
  }
 ]
}